language: csharp
solution: AccountingNET.sln
install:
  - nuget restore AccountingNET.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release AccountingNET.sln
  - mono ./testrunner/NUnit.Runners.3.6.0/tools/nunit-console.exe ./Accounting.NET/Accounting.Tests/bin/AccountingNET.Tests.dll