version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_test:
  - ps: >-
    mkdir coverage-results
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.6.0\nunit3-console.exe" -targetargs:"/nologo /noshadow .\Accounting.Tests\bin\Release\AccountingNET.Tests.dll -noshadow" "-filter:+[*]* -[AccountingNET.Tests*]*" -skipautoprops -output:.\coverage-results\results.xml
    .\packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover --input .\coverage-results\results.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
